apiVersion: apps/v1
kind: Deployment
metadata:
  name: kargo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kargo-demo
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - image: ghcr.io/maxflanderslaerdal/kargo-demo:sha-3e83de7
        name: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          name: content
          readOnly: true
          subPath: index.html
      volumes:
      - configMap:
          name: kargo-demo-content
        name: content
