apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-demo-content
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>uat</title>
    </head>
    <body>

    <h1>uat</h1>
    <div id="additional-content">
      <iframe src="additional.html" width="100%" height="500px" style="border:none;"></iframe>
    </div>

    </body>
    </html>
